~/bayesian/dashboard/repositories/fabric8-analytics-auth ~/bayesian/dashboard/repositories/fabric8-analytics-auth
Already using interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3
Not overwriting existing python script /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python (you must use /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-auth/venv/bin/python3)
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /home/ptisnovs/bayesian/fabric8-analytics-common/dashboard/venv/bin/python3
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.1.1)
----------------------------------------------------
Checking source files for common errors in following
directories:
fabric8a_auth
tests
tools
----------------------------------------------------

fabric8a_auth/auth.py
    Pass
fabric8a_auth/__init__.py
    Pass
fabric8a_auth/errors.py
    Pass
tests/test_errors_class.py
    Pass
tests/__init__.py
    Pass
tests/test_utility_functions.py
    Pass
tests/test_token_handling.py
    Pass
tools/check_python_version.py
    Pass
----------------------------------------------------
Checking following source files for common errors:
setup.py
----------------------------------------------------

setup.py
    Pass
~/bayesian/dashboard/repositories/fabric8-analytics-auth
All checks passed for 9 source files
